directory: ~/Music/AutoAddiTunes
library: ~/Music/musiclibrary.blb

import:
    copy: no
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: folder
plugins: embedart chroma fetchart web
pluginpath: ~/beets/myplugins
threaded: yes
color: yes
match:
    strong_rec_thresh: 0.55

paths:
    default: $albumartist/$album/$track - $title - $artist
    singleton: Singletons/$artist - $title
    comp: Compilation/$album/$track - $title - $artist
    albumtype:soundtrack: Soundtracks/$album/$track - $title - $artist
